apiVersion: v1
kind: Service
metadata:
  name: myapp-service-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: myapp-app-loadbalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
